const app=document.getElementById("app")||document.body;
app.innerHTML=`<style>
:root{color-scheme:dark;--b:#0e0e10;--p:#18181b;--p2:#222226;--t:#f5f5f5;--m:#9999a1;--l:#33333a;--g:#e8bd59}*{box-sizing:border-box}body{margin:0;background:var(--b);color:var(--t);font:13px/1.45 Inter,system-ui,-apple-system,sans-serif}.w{display:grid;grid-template-columns:minmax(260px,1fr) 300px;gap:12px;padding:12px}.pv{min-height:430px;border:1px solid var(--l);border-radius:14px;display:grid;place-items:center;overflow:hidden;background:linear-gradient(45deg,#17171a 25%,transparent 25%),linear-gradient(-45deg,#17171a 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#17171a 75%),linear-gradient(-45deg,transparent 75%,#17171a 75%);background-size:20px 20px;background-position:0 0,0 10px,10px -10px,-10px 0}.pv canvas{max-width:100%;max-height:72vh}.c{border:1px solid var(--l);border-radius:14px;background:var(--p);padding:14px;display:flex;flex-direction:column;gap:11px}.h{font-size:16px;font-weight:700}.s,.st{color:var(--m);font-size:12px}label{display:grid;gap:5px}select,input{width:100%;height:34px;border:1px solid var(--l);border-radius:8px;background:var(--p2);color:var(--t);padding:0 8px}.r{display:grid;grid-template-columns:1fr 1fr;gap:8px}.btn{height:38px;border-radius:9px;border:1px solid #624d25;background:#2c220f;color:#f3d481;font-weight:700;cursor:pointer}.btn:disabled{opacity:.45}.st{padding:8px;border:1px solid var(--l);border-radius:8px;background:#111113}.dl a{display:block;margin-top:6px;padding:8px;border:1px solid var(--l);border-radius:8px;color:#f3d481;text-decoration:none}@media(max-width:700px){.w{grid-template-columns:1fr}.pv{min-height:320px}}</style>
<div class=w><div class=pv><canvas id=cv></canvas></div><div class=c><div><div class=h>SVGA Editor</div><div class=s>Preview locally in ChatGPT, then export.</div></div>
<label>Effect<select id=pr><option value=vip>VIP combo</option><option value=shine>Shine</option><option value=glow>Glow</option><option value=particles>Particles</option><option value=fade>Fade</option><option value=pulse>Pulse</option><option value=float>Float</option></select></label>
<div class=r><label>Duration<input id=du type=number min=1 max=6 step=.5 value=3></label><label>FPS<select id=fp><option>10</option><option selected>12</option><option>15</option></select></label></div>
<label>Intensity<input id=it type=range min=.1 max=1 step=.05 value=.7></label><label>Accent<input id=ac type=color value=#e8bd59></label>
<button class=btn data-f=svga>Export SVGA</button><button class=btn data-f=gif>Export GIF</button><button class=btn data-f=webp>Export WebP</button><div id=st class=st>Waiting for an image…</div><div id=dl class=dl></div><div class=s>First release: max preview/export edge 640px; animated inputs use the first decoded frame.</div></div></div>`;
const $=id=>document.getElementById(id),cv=$("cv"),x=cv.getContext("2d",{alpha:true,willReadFrequently:true});
const S={img:null,file:"asset.png",id:"",run:true,seed:1,out:null};let P=[];
const cfg=()=>({preset:$("pr").value,duration:Math.max(1,Math.min(6,+$("du").value||3)),fps:+$("fp").value||12,intensity:+$("it").value||.7,accent:$("ac").value||"#e8bd59"});
function seed(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rnd(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function rgba(h,a){const v=parseInt(h.slice(1),16);return`rgba(${v>>16&255},${v>>8&255},${v&255},${a})`}
function mkP(){const r=rnd(S.seed);P=Array.from({length:26},()=>({x:r(),y:r(),z:.8+r()*2.4,p:r()*6.283,s:.55+r()*1.2,d:(r()-.5)*.08}))}
function src(t,a=1,sc=1,dy=0,g=0){x.save();x.globalAlpha=a;x.translate(cv.width/2,cv.height/2+dy);x.scale(sc,sc);if(g){x.shadowColor=cfg().accent;x.shadowBlur=g*Math.min(cv.width,cv.height)*.05}x.drawImage(S.img,-cv.width/2,-cv.height/2,cv.width,cv.height);x.restore()}
function shine(t){const c=cfg(),q=document.createElement("canvas");q.width=cv.width;q.height=cv.height;const y=q.getContext("2d"),p=(t*1.35-.2)*(cv.width+cv.height),g=y.createLinearGradient(p-cv.width*.35,0,p+cv.width*.35,cv.height);g.addColorStop(0,"transparent");g.addColorStop(.48,rgba(c.accent,0));g.addColorStop(.5,rgba(c.accent,.9*c.intensity));g.addColorStop(.55,"transparent");y.fillStyle=g;y.fillRect(0,0,q.width,q.height);y.globalCompositeOperation="destination-in";y.drawImage(S.img,0,0,q.width,q.height);x.save();x.globalCompositeOperation="screen";x.drawImage(q,0,0);x.restore()}
function particles(t){const c=cfg();x.save();x.globalCompositeOperation="screen";for(const p of P){const w=(t*p.s+p.p/6.283)%1,a=Math.max(0,Math.sin(w*Math.PI))*c.intensity,px=(p.x+p.d*Math.sin(t*6.283+p.p))*cv.width,py=(p.y-.07*w)*cv.height,r=p.z*(.75+.4*Math.sin(t*6.283+p.p)),g=x.createRadialGradient(px,py,0,px,py,r*3);g.addColorStop(0,rgba(c.accent,a));g.addColorStop(.3,rgba(c.accent,a*.55));g.addColorStop(1,rgba(c.accent,0));x.fillStyle=g;x.beginPath();x.arc(px,py,r*3,0,6.283);x.fill()}x.restore()}
function frame(t){if(!S.img)return;const c=cfg(),w=Math.sin(t*6.283);x.clearRect(0,0,cv.width,cv.height);let a=1,sc=1,dy=0,g=0;if(c.preset==="fade")a=.12+.88*(.5-.5*Math.cos(t*6.283));if(c.preset==="pulse"||c.preset==="vip")sc=1+w*.035*c.intensity;if(c.preset==="float")dy=w*cv.height*.025*c.intensity;if(c.preset==="glow"||c.preset==="vip")g=(.5+.5*w)*c.intensity;src(t,a,sc,dy,g);if(c.preset==="shine"||c.preset==="vip")shine(t);if(c.preset==="particles"||c.preset==="vip")particles(t)}
function tick(n){if(S.img&&S.run){const c=cfg();frame(((n/1000)%c.duration)/c.duration)}requestAnimationFrame(tick)}requestAnimationFrame(tick);
async function fileUrl(out){if(out.source_proxy_url)return out.source_proxy_url;if(window.openai?.getFileDownloadUrl&&out.file_id){const r=await window.openai.getFileDownloadUrl({fileId:out.file_id});if(r?.downloadUrl)return r.downloadUrl}return out.download_url||""}
async function load(out){if(!out?.file_id)return;S.out=out;S.id=out.file_id;S.file=out.file_name||"asset.png";for(const [k,id] of [["preset","pr"],["duration","du"],["fps","fp"],["intensity","it"]])if(out[k]!=null)$(id).value=out[k];if(out.accent_color)$("ac").value=out.accent_color;$("st").textContent="Loading image…";const u=await fileUrl(out),r=await fetch(u);if(!r.ok)throw Error("Image download failed "+r.status);const b=await r.blob(),im=await createImageBitmap(b),m=640,s=Math.min(1,m/Math.max(im.width,im.height));cv.width=Math.max(1,Math.round(im.width*s));cv.height=Math.max(1,Math.round(im.height*s));S.img=im;S.seed=seed(out.job_id||out.file_id);mkP();$("st").textContent=`Ready · ${cv.width}×${cv.height}`;sync()}
function apply(o){const d=o?.structuredContent||o;if(d?.file_id)load(d).catch(e=>$("st").textContent="Load failed: "+e.message)}
let rid=0;const pend=new Map();function req(method,params){return new Promise((resolve,reject)=>{const id=++rid;pend.set(id,{resolve,reject});parent.postMessage({jsonrpc:"2.0",id,method,params},"*")})}
addEventListener("message",e=>{if(e.source!==parent)return;const m=e.data;if(!m||m.jsonrpc!=="2.0")return;if(typeof m.id==="number"&&pend.has(m.id)){const p=pend.get(m.id);pend.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);return}if(m.method==="ui/notifications/tool-result")apply(m.params)});
(async()=>{if(window.openai?.toolOutput)apply(window.openai.toolOutput);try{await req("ui/initialize",{appInfo:{name:"svga-editor-widget",version:"0.1.0"},appCapabilities:{},protocolVersion:"2026-07-28"});parent.postMessage({jsonrpc:"2.0",method:"ui/notifications/initialized",params:{}},"*")}catch{}})();
function sync(){if(!S.id||!window.openai?.setWidgetState)return;const c=cfg();window.openai.setWidgetState({modelContent:`SVGA Editor settings: effect=${c.preset}, duration=${c.duration}s, fps=${c.fps}, intensity=${c.intensity}, accent=${c.accent}`,privateContent:{...c,fileName:S.file},imageIds:[S.id]})}
["pr","du","fp","it","ac"].forEach(id=>$(id).addEventListener("input",sync));
const a=s=>new TextEncoder().encode(s),u16=n=>new Uint8Array([n&255,n>>>8&255]),u24=n=>new Uint8Array([n&255,n>>>8&255,n>>>16&255]),u32=n=>new Uint8Array([n&255,n>>>8&255,n>>>16&255,n>>>24&255]);
function cat(ps){const n=ps.reduce((s,p)=>s+p.length,0),o=new Uint8Array(n);let k=0;for(const p of ps){o.set(p,k);k+=p.length}return o}
function chunk(tag,p){return cat([a(tag),u32(p.length),p,p.length%2?new Uint8Array([0]):new Uint8Array])}
const blob=(type,q)=>new Promise((ok,no)=>cv.toBlob(b=>b?ok(b):no(Error("Encode failed")),type,q));
async function at(i,n){frame(i/n);await new Promise(r=>requestAnimationFrame(r))}
function pal(){const p=new Uint8Array(768),L=[0,51,102,153,204,255];let i=1;for(let r=0;r<6;r++)for(let g=0;g<6;g++)for(let b=0;b<6;b++){p[i*3]=L[r];p[i*3+1]=L[g];p[i*3+2]=L[b];i++}return p}
function idx(d){const o=new Uint8Array(d.length/4);for(let i=0,j=0;i<d.length;i+=4,j++){if(d[i+3]<24){o[j]=0;continue}o[j]=1+Math.min(5,Math.round(d[i]/51))*36+Math.min(5,Math.round(d[i+1]/51))*6+Math.min(5,Math.round(d[i+2]/51))}return o}
function lzw(data){const clear=256,end=257;let size=9,next=258,D=new Map,buf=0,bits=0,out=[];const wr=c=>{buf|=c<<bits;bits+=size;while(bits>=8){out.push(buf&255);buf>>>=8;bits-=8}},reset=()=>{size=9;next=258;D=new Map};wr(clear);let p=data[0]||0;for(let i=1;i<data.length;i++){const k=data[i],key=p+","+k;if(D.has(key)){p=D.get(key);continue}wr(p);if(next<4096){D.set(key,next++);if(next===(1<<size)&&size<12)size++}else{wr(clear);reset()}p=k}wr(p);wr(end);if(bits)out.push(buf&255);return new Uint8Array(out)}
function blocks(d){const p=[];for(let i=0;i<d.length;i+=255){const s=d.slice(i,i+255);p.push(new Uint8Array([s.length]),s)}p.push(new Uint8Array([0]));return cat(p)}
async function gif(){const c=cfg(),n=Math.round(c.duration*c.fps),delay=Math.max(2,Math.round(100/c.fps)),p=[a("GIF89a"),u16(cv.width),u16(cv.height),new Uint8Array([247,0,0]),pal(),new Uint8Array([33,255,11]),a("NETSCAPE2.0"),new Uint8Array([3,1,0,0,0])];for(let i=0;i<n;i++){await at(i,n);const z=lzw(idx(x.getImageData(0,0,cv.width,cv.height).data));p.push(new Uint8Array([33,249,4,9]),u16(delay),new Uint8Array([0,0]),new Uint8Array([44]),u16(0),u16(0),u16(cv.width),u16(cv.height),new Uint8Array([0,8]),blocks(z));$("st").textContent=`GIF ${i+1}/${n}`}p.push(new Uint8Array([59]));return new Blob([cat(p)],{type:"image/gif"})}
function webpParts(bytes){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),out=[];let o=12;while(o+8<=bytes.length){const tag=String.fromCharCode(...bytes.slice(o,o+4)),n=v.getUint32(o+4,true),e=o+8+n;if(e>bytes.length)break;if(tag==="ALPH"||tag==="VP8 "||tag==="VP8L")out.push(chunk(tag,bytes.slice(o+8,e)));o=e+(n%2)}if(!out.length)throw Error("WebP frame parse failed");return out}
async function webp(){const c=cfg(),n=Math.round(c.duration*c.fps),ms=Math.max(20,Math.round(1000/c.fps)),fs=[];for(let i=0;i<n;i++){await at(i,n);const b=await blob("image/webp",.86),s=webpParts(new Uint8Array(await b.arrayBuffer())),h=cat([u24(0),u24(0),u24(cv.width-1),u24(cv.height-1),u24(ms),new Uint8Array([2])]);fs.push(chunk("ANMF",cat([h,...s])));$("st").textContent=`WebP ${i+1}/${n}`}const vp=chunk("VP8X",cat([new Uint8Array([18,0,0,0]),u24(cv.width-1),u24(cv.height-1)])),an=chunk("ANIM",new Uint8Array(6)),pay=cat([a("WEBP"),vp,an,...fs]);return new Blob([cat([a("RIFF"),u32(pay.length),pay])],{type:"image/webp"})}
function vv(n){const q=[];let v=n>>>0;while(v>127){q.push((v&127)|128);v>>>=7}q.push(v);return new Uint8Array(q)}function tag(f,w){return vv(f<<3|w)}function pb(f,b){return cat([tag(f,2),vv(b.length),b])}function ps(f,s){return pb(f,a(s))}function pf(f,n){const b=new Uint8Array(4);new DataView(b.buffer).setFloat32(0,n,true);return cat([tag(f,5),b])}function pi(f,n){return cat([tag(f,0),vv(n)])}function pm(f,p){return pb(f,cat(p))}const lay=(w,h)=>cat([pf(1,0),pf(2,0),pf(3,w),pf(4,h)]),tr=()=>cat([pf(1,1),pf(2,0),pf(3,0),pf(4,1),pf(5,0),pf(6,0)]),fr=(al,w,h)=>cat([pf(1,al),pm(2,[lay(w,h)]),pm(3,[tr()])]);
async function deflate(b){const c=new CompressionStream("deflate"),w=c.writable.getWriter();w.write(b);w.close();return new Uint8Array(await new Response(c.readable).arrayBuffer())}
async function svga(){const c=cfg(),n=Math.round(c.duration*c.fps),imgs=[],spr=[],png=[];for(let i=0;i<n;i++){await at(i,n);png.push(new Uint8Array(await(await blob("image/png")).arrayBuffer()));$("st").textContent=`SVGA ${i+1}/${n}`}for(let i=0;i<n;i++){const k="f"+String(i).padStart(3,"0");imgs.push(pm(3,[cat([ps(1,k),pb(2,png[i])])]));const fs=[];for(let j=0;j<n;j++)fs.push(pm(2,[fr(i===j?1:0,cv.width,cv.height)]));spr.push(pm(4,[ps(1,k),...fs]))}const param=cat([pf(1,cv.width),pf(2,cv.height),pi(3,c.fps),pi(4,n)]),movie=cat([ps(1,"2.0"),pm(2,[param]),...imgs,...spr]);return new Blob([await deflate(movie)],{type:"application/octet-stream"})}
async function expose(b,f){const base=(S.file||"asset").replace(/\.[^.]+$/,"").replace(/[^a-zA-Z0-9_-]+/g,"_")||"asset",file=new File([b],`${base}-${cfg().preset}.${f}`,{type:f==="svga"?"application/octet-stream":"image/"+f});let href=URL.createObjectURL(file);if(window.openai?.uploadFile)try{const u=await window.openai.uploadFile(file,{library:false});if(u?.fileId&&window.openai.getFileDownloadUrl){const d=await window.openai.getFileDownloadUrl({fileId:u.fileId});if(d?.downloadUrl)href=d.downloadUrl}}catch{}const l=document.createElement("a");l.href=href;l.target="_blank";l.rel="noopener";l.download=file.name;l.textContent=`Download ${f.toUpperCase()} · ${(b.size/1048576).toFixed(2)} MB`;$("dl").prepend(l)}
async function go(f){if(!S.img)return;$("st").textContent="Preparing "+f.toUpperCase()+"…";document.querySelectorAll("[data-f]").forEach(b=>b.disabled=true);S.run=false;try{const b=f==="gif"?await gif():f==="webp"?await webp():await svga();await expose(b,f);$("st").textContent=f.toUpperCase()+" ready"}catch(e){console.error(e);$("st").textContent="Export failed: "+e.message}finally{S.run=true;document.querySelectorAll("[data-f]").forEach(b=>b.disabled=false)}}
document.querySelectorAll("[data-f]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.f)));
